apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
strategy:
  type: Recreate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: backend
        image: todo-backend:1.3
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend
spec:
  type: NodePort
  selector:
    app: todo-backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30001
