apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-mysql
  template:
    metadata:
      labels:
        app: todo-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: todo_db
        ports:
        - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: todo-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: todo-mysql
