apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-wrong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginxx           # ❌ galat label - "nginx" hona chahiye tha
    spec:
      containers:
        - name: nginx
          image: nginx:wrongtag    # ❌ galat image tag - "wrongtag" exists nahi karta
          ports:
            - containerPort: 80
